services:
  backend:
    container_name: E_Health_backend_con
    env_file:
      - ./Backend/.env
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - database   

  frontend:
    container_name: E_Health_frontend_con
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: mongo:8.0.3
    container_name: E_Health_db_con
    ports:
      - "27017:27017"